export const appImages = {
  awarenessAlert: require('../../assets/awareness/alert.png'),
  awarenessCalm: require('../../assets/awareness/Background.png'),
  resultMap: require('../../assets/awareness/resultmap-Icon.png'),
  awarenessExcitement: require('../../assets/awareness/excitement.png'),
  awarenessExpansionCompassion: require('../../assets/awareness/expansion/Background-1.png'),
  awarenessExpansionProtection: require('../../assets/awareness/expansion/Background-2.png'),
  awarenessExpansionJoy: require('../../assets/awareness/expansion/Background.png'),
  awarenessExpansionSurprise: require('../../assets/awareness/expansion/Container.png'),
  awarenessExpansionRepress: require('../../assets/awareness/expansion/image 26.png'),
  awarenessExpansionSpiral: require('../../assets/awareness/expansion/sprailing.png'),
  awarenessIrritation: require('../../assets/awareness/Irritation visualization.png'),
  awarenessResilient: require('../../assets/awareness/Resilient visualization.png'),
  awarenessStuck: require('../../assets/awareness/Stuck visualization.png'),
  courseExerciseIllustration: require('../../assets/navbar/Exercise Streamline Lagos.png'),
  courseMeditationIllustration: require('../../assets/navbar/Meditation Streamline Lagos.png'),
  courseReflectIllustration: require('../../assets/navbar/Group.png'),
  courseTaskListIllustration: require('../../assets/navbar/Task-List Streamline Manchester.png'),
  emotionalSignalIcon: require('../../assets/images/emotional-signal.png'),
  loginHero: require('../../assets/images/loginImage.png'),
  navBookmarkActive: require('../../assets/navbar/Bookmark-white.png'),
  navBookmarkInactive: require('../../assets/navbar/Bookmark.png'),
  navHomeActive: require('../../assets/navbar/home-white (2).png'),
  navHomeInactive: require('../../assets/navbar/Home.png'),
  navProfileActive: require('../../assets/navbar/Profile-white.png'),
  navProfileInactive: require('../../assets/navbar/Profile.png'),
  navVideoActive: require('../../assets/navbar/Video-white.png'),
  navVideoInactive: require('../../assets/navbar/Video.png'),
  observationGrowthIcon: require('../../assets/images/observation-growth-logo.png'),
  observationIcon: require('../../assets/images/observation-logo.png'),
  onboardingJourney: require('../../assets/images/onboarding2.png'),
  onboardingLogo: require('../../assets/images/onboarding1.png'),
  physiologicalIcon: require('../../assets/images/psychological-logo.png'),
  reflectionIcon: require('../../assets/images/reflection-logo.png'),
  HumanMap: require('../../assets/somatic/Somatic_Map_Container_margin.png'),
  Brightness: require('../../assets/somatic/brightnesss&clear.png'),
  HeavyFog: require('../../assets/somatic/Background+HorizontalBorder.png'),
  Dizzy: require('../../assets/somatic/dizyy.png'),
  Neural: require('../../assets/somatic/Neural_Energy_Field.png'),
  
  Flexiblity: require('../../assets/somatic/flexibility.png'),
  Cognitive: require('../../assets/somatic/cognitive.png'),
  HumanFace: require('../../assets/somatic/throat/humanface.png'),
  jaw: require('../../assets/somatic/throat/jaw.png'),
  Female: require('../../assets/somatic/throat/female.png'),
  Illustration: require('../../assets/somatic/throat/Illustration-men.png'),
  ChestOpening: require('../../assets/somatic/throat/chest-opening.png'),

  ChestHuman: require('../../assets/chest/human-body-dia.png'),
  Breath360: require('../../assets/chest/360-breath.png'),
  ChestLighterSoldier: require('../../assets/chest/chest-lighter-soldier.png'),

  SafetyCue: require('../../assets/stomach/safety-cue.png'),

  ShoulderDrop: require('../../assets/handslegs/shoulder-drop.png'),
  RthymicGrounding: require('../../assets/handslegs/rthymic-grounding.png'),
  Proprioception: require('../../assets/handslegs/proprioception.png'),
  FistClench: require('../../assets/handslegs/fist-clench.png'),

  PatternAwarenessSignature: require('../../assets/pattern-awareness/Biological-Signature.png'),
  FogVsFatigue: require('../../assets/somatic/heaviness-fog/Button - Card 3_ Heaviness/Abstract Visualization 3.png'),
} as const;
